version: 2

updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: daily
      time: '21:00'
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: '21:00'
