name: Tests

on: push

jobs:
  php-tests:
    runs-on: ubuntu-latest

    name: PHP Static

    steps:
      - name: Checkout CPT Editor repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run 'phpcs' check
        run: composer test:style

      - name: Run 'phpstan' check
        run: composer test:static
